### ISSUE TITLE
pysubs2 detecting "," in text as new param

### ISSUE THREAD

**Issue by latot** [tkarabela/pysubs2#16]
Hi, i found this bug..., basically this:

```
﻿[Script Info]
Title: Bugs in the window
ScriptType: v4.00

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0000,0000,0000,,Hi, i'm new here
```

This will works in the reproducer but will fails in pysubs2, in the text field, the "," is interpreted as a new param and fails with:

```
AttributeError: 'NoneType' object has no attribute 'groups'
```

Bye.

**Comment by tkarabela** [comment]
Do you have a full stack trace for this?

I believe pysubs2 has a hard time recognizing that as a SubStation file, since it is missing the styles section. In the SubStation parser, commas in dialogue text are handled (it would break with almost any real-world file otherwise).

**Comment by latot** [comment]
Hi, sorry for this, the script was with problems, i test this again anyway and works fine.

For some reason the player works fine with this format in the time 0:01:19.24 and 0:01:19:24, maybe this can be a bug?, or the player just reconginze something out of the specs?

Bye.

**Comment by latot** [comment]
i'll close this and open a new bug report with the right topic.
